ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true 
    publish_tf: true

    #map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom 

    # 只接收 IMU
    imu0: imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]

    imu0_differential: true
    imu0_remove_gravitational_acceleration: true

    # imu_base_odom
    # odom0: /odometry/imu_velocity
    # odom0_config: [true, true, false,
    #                true,  true,  false,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false]

    # odom0_differential: false
    # use_control: false
    

