ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true 

    # 只接收 IMU
    imu0: imu/data
    imu0_config: [false, false, false,   # x y z 位置
                  false, false, false,   # x y z 速度
                  false, false, false,    # orientation
                  false, false, true]    # angular velocity

    odom0: /odometry/imu_velocity
    odom0_config: [false, false, false,  # x y z 位置
                   true,  true,  false,  # x y z 速度
                   false, false, false, # orientation
                   false, false, false] # angular velocity

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    odom0_differential: true

    use_control: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom  # 若用 GPS 才會用 map